# Generated by Django 5.2.14 on 2026-06-01 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel_type', models.CharField(choices=[('group', 'Group'), ('direct', 'Direct'), ('announcement', 'Announcement')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='communities.community')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='users.organization')),
            ],
            options={
                'db_table': 'messaging_channel',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField()),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.channel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='users.userprofile')),
            ],
            options={
                'db_table': 'messaging_channelmember',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('moderation_status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='visible', max_length=16)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.channel')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='users.organization')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.userprofile')),
            ],
            options={
                'db_table': 'messaging_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['organization'], name='channel_org_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(condition=models.Q(('community_id__isnull', False)), fields=['community'], name='channel_community_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['organization', 'channel_type'], name='channel_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmember',
            index=models.Index(fields=['user', 'channel'], name='channel_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelmember',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='channel_member_uniq'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', '-created_at'], name='message_channel_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='message_sender_created_idx'),
        ),
    ]
