# Generated by Django 5.2.14 on 2026-06-01 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField()),
                ('moderation_status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='visible', max_length=16)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='users.userprofile')),
                ('community', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='community_posts', to='users.organization')),
            ],
            options={
                'db_table': 'messaging_communitypost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('moderation_status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='visible', max_length=16)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='users.userprofile')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to='users.organization')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.postcomment')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.communitypost')),
            ],
            options={
                'db_table': 'messaging_postcomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['community', '-created_at'], name='post_community_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['post', 'created_at'], name='comment_post_created_idx'),
        ),
    ]
