# Generated by Django 5.2.14 on 2026-06-01 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_posts_and_comments'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('care', 'Care'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='post_reactions', to='users.organization')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.communitypost')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='users.userprofile')),
            ],
            options={
                'db_table': 'messaging_postreaction',
                'indexes': [models.Index(fields=['post', 'reaction_type'], name='post_reaction_post_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='post_reaction_user_uniq')],
            },
        ),
    ]
