# Generated by Django 5.2.14 on 2026-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
