#!/usr/bin/env bash
# Prepare Google OAuth credentials for Cognito social sign-in and apply Cognito config.
#
# Google Cloud does not expose standard OAuth 2.0 Web Client CRUD via gcloud.
# This script:
#   1. Resolves client ID/secret from cognito-social-auth.env or .env.local
#   2. Prints the Cognito IdP redirect URI to register in Google Cloud Console
#   3. Runs infrastructure/aws/configure-cognito-social-auth.sh
#
# Usage:
#   ./infrastructure/google/setup-cognito-google-oauth.sh
#
# Optional env (in cognito-social-auth.env or .env.local):
#   GOOGLE_COGNITO_CLIENT_ID / GOOGLE_COGNITO_CLIENT_SECRET  (preferred, Web client)
#   GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET                  (cognito-social-auth.env)
#   GOOGLE_TASKS_OAUTH_CLIENT_ID / GOOGLE_TASKS_OAUTH_CLIENT_SECRET (fallback)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COGNITO_ENV="$ROOT/infrastructure/aws/cognito-social-auth.env"
COGNITO_REDIRECT="${COGNITO_IDP_REDIRECT_URI:-https://us-east-1ruftimytf.auth.us-east-1.amazoncognito.com/oauth2/idpresponse}"
GCP_PROJECT="${GOOGLE_CLOUD_PROJECT:-boxwood-magnet-498623-n4}"

load_env_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -n "$line" ]] || continue
    [[ "$line" == *"="* ]] || continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(printf '%s' "$key" | sed 's/[[:space:]]*$//')"
    value="$(printf '%s' "$value" | sed 's/^[[:space:]]*//')"
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi
    if ! printenv "$key" >/dev/null 2>&1; then
      export "$key=$value"
    fi
  done <"$file"
}

load_env_file "$COGNITO_ENV"
load_env_file "$ROOT/.env.local"

GOOGLE_ID="${GOOGLE_COGNITO_CLIENT_ID:-${GOOGLE_CLIENT_ID:-${GOOGLE_TASKS_OAUTH_CLIENT_ID:-}}}"
GOOGLE_SECRET="${GOOGLE_COGNITO_CLIENT_SECRET:-${GOOGLE_CLIENT_SECRET:-${GOOGLE_TASKS_OAUTH_CLIENT_SECRET:-}}}"

if [[ -z "$GOOGLE_ID" || -z "$GOOGLE_SECRET" ]]; then
  echo "Missing Google OAuth credentials." >&2
  echo "Set GOOGLE_COGNITO_CLIENT_ID and GOOGLE_COGNITO_CLIENT_SECRET in:" >&2
  echo "  infrastructure/aws/cognito-social-auth.env" >&2
  echo "or reuse GOOGLE_TASKS_OAUTH_* from .env.local (Web client with Cognito redirect added)." >&2
  exit 1
fi

mkdir -p "$(dirname "$COGNITO_ENV")"
cat >"$COGNITO_ENV" <<EOF
# Generated by infrastructure/google/setup-cognito-google-oauth.sh — gitignored
AWS_REGION=us-east-1
COGNITO_USER_POOL_ID=us-east-1_rUfTimytf
COGNITO_APP_CLIENT_ID=4t0uapt8havig5h7jiio9g9os4
COGNITO_HOSTED_UI_DOMAIN=us-east-1ruftimytf.auth.us-east-1.amazoncognito.com
COGNITO_IDP_REDIRECT_URI=$COGNITO_REDIRECT

GOOGLE_CLIENT_ID=$GOOGLE_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_SECRET
EOF

echo "Google OAuth client for Cognito"
echo "  Project : $GCP_PROJECT"
echo "  Client  : $GOOGLE_ID"
echo ""
echo "Register this Authorized redirect URI on the Web OAuth client in Google Cloud:"
echo "  $COGNITO_REDIRECT"
echo ""
echo "Console (edit client):"
echo "  https://console.cloud.google.com/auth/clients?project=$GCP_PROJECT"
echo ""
echo "Cognito Google scopes (already set by configure script): profile email openid"
echo ""

"$ROOT/infrastructure/aws/configure-cognito-social-auth.sh"
