# Generated by Django 5.2.14 on 2026-06-03 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_type', models.CharField(choices=[('pregnancy', 'Pregnancy'), ('newborn', 'Newborn'), ('postpartum', 'Postpartum')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_community', models.ForeignKey(blank=True, db_column='linked_community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_cohorts', to='communities.community')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='users.organization')),
            ],
            options={
                'db_table': 'cohorts_cohort',
            },
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('recommended', 'Recommended')], default='auto', max_length=16)),
                ('assigned_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(db_column='cohort_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cohorts.cohort')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='cohort_memberships', to='users.organization')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='users.userprofile')),
            ],
            options={
                'db_table': 'cohorts_membership',
            },
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['organization', 'cohort_type', 'is_active'], name='cohort_org_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('user', 'cohort'), name='cohort_mbr_user_cohort_uniq'),
        ),
    ]
